const {
    PORT,
    NODE_ENV,
    CLIENT_URL,
    FRONTEND_URL,
    MONGODB_URL,
    SENDER_EMAIL,
    DATABASE_PASSWORD,
    USER,
    MONGODB_LOCAL,
    JWT_SECRET,
    JWT_EXPIRES_IN,
    JWT_EXPIRES_COOKIES
} = process.env;

module.exports = {
    PORT,
    NODE_ENV,
    CLIENT_URL,
    FRONTEND_URL,
    MONGODB_URL,
    SENDER_EMAIL,
    DATABASE_PASSWORD,
    USER,
    MONGODB_LOCAL,
    JWT_SECRET,
    JWT_EXPIRES_IN,
    JWT_EXPIRES_COOKIES
};
